<img id="bgImg" src="<?php echo $this->baseURL();?>/graphics/background_dark.jpg" >
<div id="bodyDiv">
	<div id="logosmallDiv"><img id="logosmallImg" src="<?php echo $this->baseURL();?>/graphics/logo_small.jpg" "></div>
	<div id="contentsmallDiv">
		<div id="content">
			<div id="name">
				<normaltext><br>You have insufficient credentials for the selected action!</normaltext>
			</div>
			<dl>
			<p><a href="<?php echo $this->url(
			array(
			'controller' => 'account',
			'action'     => 'index'
			),
			'default',
			true)?>">Back to Accounts</a></p>
			</dl>
		</div>
	</div>
</div>