<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<?php echo $this->headScript()->appendFile($this->baseUrl('/../library/datepicker/compressed/picker.js'));?>
	<?php echo $this->headScript()->appendFile($this->baseUrl('/../library/datepicker/compressed/picker.date.js'));?>
	<?php echo $this->headScript()->appendFile($this->baseUrl('/../library/datepicker/themes/default.css'));?>
	<?php echo $this->headScript()->appendFile($this->baseUrl('/../library/datepicker/themes/default.date.css'));?>
</head>
<body>
<div>
    <headline><br>edit Entry</headline>
</div>

<?php 
$this->form->setAction($this->url() . '?id=' . $this->id);
echo $this->form;
?>

<script>
$('#date').on('click', function(){
	$('#date').pickadate({
	  format: 'yyyy-mm-dd',
	  formatSubmit: 'yyyy-mm-dd'
	});
});
/*$('#date').focusout(function(){
	$('#date').pickadate().close();
});*/
</script>

<dl>
   <p><a href="<?php echo $this->url(
        array(
        'controller' => 'accountdetail',
        'action'     => 'index'
        ),
        'default',
        true) . '?id=' . $this->accId ?>">back</a></p>
</dl>
</body>