<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script type="text/javascript" src = "../library/datepicker/compressed/picker.js"></script>
	<script type="text/javascript" src = "../library/datepicker/compressed/picker.date.js"></script>
	<script src = "../library/datepicker/themes/default.css"></script>
	<script src = "../library/datepicker/themes/default.date.css"></script>
</head>
<body>
<div>
    <headline><br>edit Entry</headline>
</div>

<?php 
$this->form->setAction($this->url() . '?id=' . $this->id);
echo $this->form;
?>

<script>
/*$(document).ready(function(){
	$(function(){
		$('#datepicker').pickadate();
	});
});*/
/*$('.datepicker').pickadate({
  format: 'yyyy-mm-dd',
  formatSubmit: 'yyyy-mm-dd'
});*/
</script>

<dl>
   <p><a href="<?php echo $this->url(
        array(
        'controller' => 'accountdetail',
        'action'     => 'index'
        ),
        'default',
        true) . '?id=' . $this->accId ?>">back</a></p>
</dl>
</body>