<div id="welcome">
    <headline><br><?php echo $this->account->getName() ?></headline>
</div>

<dl>
   <p><a href="<?php echo $this->url(
        array(
        'controller' => 'accountdetail',
        'action'     => 'createentry'
        ),
        'default',
        true)?>">new entry</a></p>
</dl>
<dl>
   <p><a href="<?php echo $this->url(
        array(
        'controller' => 'accountdetail',
        'action'     => 'createcategory'
        ),
        'default',
        true)?>">new category</a></p>
</dl>

<table class="entries">
  <tr>
    <th>Category</th>
    <th>Date</th>
    <th>Price</th>
    <th>Comment</th>
  </tr>
    <?php foreach ($this->entries as $entry): ?>
      <tr>
        <td><?php echo $entry->getCostCategoryName()?></td>
        <td><?php echo $entry->getDate()?></td>
        <td><?php echo $entry->getPrice()?></td>
        <td><?php echo $entry->getComment()?></td>
      </tr>
    <?php endforeach ?>
</table>


<dl>
   <p><a href="<?php echo $this->url(
        array(
        'controller' => 'account',
        'action'     => 'index'
        ),
        'default',
        true) ?>">back</a>
        </p>
</dl>