<div id="welcome">
    <h1><?php echo $this->account->getName() ?></h1>
</div>

<dl>
   <p><a href="<?php echo $this->url(
        array(
        'controller' => 'accountdetail',
        'action'     => 'createentry'
        ),
        'default',
        true) . '?id='. $this->account->getId() ?>">new entry</a></p>
</dl>

<table class="entries">
  <tr>
    <th>Category</th>
    <th>Date</th>
    <th>Price</th>
    <th>Comment</th>
  </tr>
    <?php foreach ($this->entries as $entry): ?>
      <tr>
        <td><?php echo $entry->getCostCategoryId()?></td>
        <td><?php echo $entry->getDate()?></td>
        <td><?php echo $entry->getPrice()?></td>
        <td><?php echo $entry->getComment()?></td>
      </tr>
    <?php endforeach ?>
</table>


<dl>
   <p><a href="<?php echo $this->url(
        array(
        'controller' => 'account',
        'action'     => 'index'
        ),
        'default',
        true) ?>">back</a>
        </p>
</dl>

<?php 
echo $this->test
?>