<img id="bgImg" src="<?php echo $this->baseUrl();?>/graphics/background_dark.jpg" >
<div id="bodyDiv">
	<div id="logosmallDiv"><img id="logosmallImg" src="<?php echo $this->baseUrl();?>/graphics/logo_small.jpg" "></div>
	<div id="contentsmallDiv">
		<div id="content">
			<normaltext>
			<div>
				<br>Register:
			</div>
			<?php
			echo $this->success . '<br>' ;
			?>
			
			<p><a href="<?php echo $this->url(
				array(
					'controller' => 'index',
					'action'     => 'index'
				),
				'default',
				true) ?>">Click here to login!</a></p>
			</normaltext>
		</div>
	</div>
</div>