<div id="welcome">
    <headline><br>Welcome to myUltimateSpendings<br></headline>
    <largetext><br>Register yourself and join our ultimate web-based accounting software.
    <br>It's is easy to use, free and of course it's ultimate!<br><br></largetext>
</div>

<?php
$this->form->setAction($this->url());
echo $this->form;
if($this->confirm !== null){
    echo $this->confirm . '<br>';
}
?>

<div id="register">
    <p><a href="<?php echo $this->url(
    array(
        'controller' => 'register',
        'action'     => 'index'
    ),
    'default',
    true) ?>">Register here</a></p>
</div>