<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>multsp</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>


<style type="text/css">
  <!--
* { margin: 0;
   padding: 0;}
   
   
input{
    color: #000000; 
    font-size: 14px; 
    border: 1px solid #4c4c4c; 
    background-color: #4c4c4c; 
    height: 30px; 
    width: 300px;   
    padding: 0px;
}
   
/* Höhen- und Breitenanpassung zu 100%; Scrollbar ausblenden */
body, html{ 
           font-family: Arial, Helvetica, sans-serif;
	       width: 100%;
           height: 100%;
           overflow: hidden;}
	
headline{
	font-size: 40px;
	font-style: normal;
	color: #ffffff;
}

largetext{
	font-size: 22px;
	font-style: normal;
	color: #ffffff;
}

normaltext{
	font-size: 18px;
	font-style: normal;
	color: #ffffff;
}
 
/* BG-Image auf unterste Ebene anordnen */
#bgImg{ position: absolute;
       top: 0;
       left: 0;
       border: 0;
       z-index: 1;
       width: 100%;
       height: 100%;
}
#logoImg{ position: absolute;
       top: 0;
       left: 0;
       border: 0;
       z-index: 1;
       width: 400px;
       height: 400px;
}
/* Body-Dummy absolut über BG-Image legen; Scrollbar bei Bedarf einblenden */
#bodyDiv{ position: absolute;
         top: 0;
         left: 200;
         z-index: 2;
         overflow: auto;
         width: 100%;
         height: 100%;
         text-align: left;}
 
/* Layoutelemente */
#logoDiv{
            background: #4c4c4c;
	        width: 400px;
            height: 400px;

}
#loginDiv{
            background: #ff2a00;
	        margin-top: -400px;    
            margin-left: 400px;
            height: 400px;}
#loginContent{
            margin-left: 100px;
}
//-->
</style>
</head>
<body>
<img id="bgImg" src="<?php echo $this->baseURL();?>/graphics/background.jpg" >
<div id="bodyDiv">
    <div id="logoDiv"><img id="logoImg" src="<?php echo $this->baseURL();?>/graphics/logo_large.jpg" "></div>
    <div id="loginDiv">
        <div id="loginContent"><?php echo $this->layout()->content ?></div>
    </div>
</div>



</body>
</html>
